### ISSUE TITLE
Has google patched this?

### ISSUE THREAD

**Issue by lrosic00** [JoelGMSec/Cloudtopolis#2]
Whenever I try adding more than 2 agents, I get error message "Cannot connect to GPU backend due to usage limits in Colab".
It used to work perfectly couple months ago when I successfully added 10 agents.

**Comment by JoelGMSec** [comment]
Hi!

Tested right now and works flawlessly. Check your accounts, are probably banned for overuse.


<img width="866"  src="https://user-images.githubusercontent.com/34335312/111132059-31531e80-8579-11eb-869b-0ab9c370027d.png">

The most recommended option is to rotate the accounts or pay for Colab Pro.

Remember that you can transfer all Cloudtopolis data by simply copying the folder with the same name to another Cloud Shell or VPS.


Regards!
