### ISSUE TITLE
Getting error when trying to connect to other vps

### ISSUE THREAD

**Issue by tsikmartin** [JoelGMSec/Cloudtopolis#3]
I am unable to add another agent with a google account because i get the following error.

![image](https://user-images.githubusercontent.com/67664280/149242020-467c6626-d135-46d7-a737-0825f3f0c945.png)

I am also getting an error saying "failed to send solve"

![image](https://user-images.githubusercontent.com/67664280/149242209-9283b736-ca40-444a-9e87-2750e47aa198.png)

**Comment by JoelGMSec** [comment]
Hi,

I would need some more information to find out what is going on with your VPS connection.
Regarding the problem with the tasks, this is normal.
Eventually they all end up being sent as you can see in your image (it's a Hashtopolis bug).

I look forward to hearing from you, greetings!
