### ISSUE TITLE
Google banned usage of password cracking in colab

### ISSUE THREAD

**Issue by Scopen86** [JoelGMSec/Cloudtopolis#9]
Google suspended my account from using colab due to my use of password cracking, is there any alternative or any way to circumvent this ban?

**Comment by JoelGMSec** [comment]
I'm working on it, there will be news soon :)

**Comment by m041** [comment]
Me too please update

**Comment by m041** [comment]
Does this work on aws sagemaker studiolab which offers 4 hours of gpu runtime
